name: Trigger Dispatch

on:
  workflow_run:
    workflows: ["Docker Image Build and Push"]
    types:
      - completed
jobs:
  trigger_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository_dispatch event
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/DuongTranDangKhoa/ESMS_deploy/dispatches \
            -d '{"event_type":"trigger-event"}'
